### ISSUE TITLE
Add vector rotate functionality

### ISSUE THREAD

**Issue by BobWall23** [IronCoreLabs/ironcore-alloy#34]
Similar to rotation for deterministic encryption secrets, Alloy needs to handle the case where the vector encryption secret is being rotated. Should be handled similarly - if there are both a current secret and an in-rotation secret, preparing a vector for queries should encrypt the vector using both secrets and return both vectors.

This should work for both standalone and SaaS shield modes.

**Comment by skeet70** [comment]
I'm going to add a rotate function for vector that decrypts and re-encrypts. We'll want to have warnings all over it though, since it's floating point repeated rotations will drift the value. With the scaling factors involved this isn't likely going to be significant for most use cases. 

For complete accuracy the recommendation would be to store the encrypted original vector (using `standard`) as metadata (`M`) next to the `vector` encrypted value (`A`). Rotation would then be setting a new current secret, retrieving and decrypting that value (`M`), encrypting it with `vector` again (producing `B`), and updating the entry replacing `A` with `B` and keeping `M` the same. All the tools are there for them to do that, but we can't really set it up for them in a nice way.
